Htv3hc/feat/missing variable env
test-fullautomation/RobotFramework_AIO pull request #142
Opened 2023-09-08 10:22 UTC by huavanthong

Hi Thomas,

Could you help me review this pull request for this issue https://github.com/test-fullautomation/RobotFramework_AIO/issues/127 ?

Thank you and best regards,
Thong Hua

2023-09-08 11:07 UTC, test-fullautomation requested changes
Hi Thong,
please read my findings.
Thank you,
 Thomas

2023-09-08 11:07 UTC, test-fullautomation commented on config/build/dpkg_build/postinst.sh
> +###############################################################################
Hi Thong,
this is a usability issue:
Most of the users will not know genpackagedoc as this is only required if you contribute to our repositories and write documentation which is plantuml based.
Therefore: Please don't ask, just try to install JDK. If it fails even no error message shall be created, we just proceed installation.
Thank you,
 Thomas

2023-09-08 11:07 UTC, test-fullautomation commented on config/build/dpkg_build/set_robotenv.sh
> +        echo "No OpenJDK installation found."
Hi Thong,
Please remove this this message (No OpenJDK installation found). This is only confusing, but OpenJDK is for normal users not required.
JAVA_HOME set to ... is O.K.
Thank you,
 Thomas

2023-09-11 03:48 UTC, huavanthong commented
Hi Thomas,

I updated it. If there are any issues, please let me know.

Thank you and best regards,
Thong Hua

2023-09-11 10:40 UTC, test-fullautomation approved these changes
Hi Thong,
very good!
Thank you,
 Thomas

2023-09-11 10:40 UTC, merged