Insert more information so that other users can read it.
test-fullautomation/RobotFramework_AIO pull request #188
Opened 2023-11-24 08:33 UTC by huavanthong

Hi Thomas,

I have updated the additional information as per Holger's comments https://github.com/test-fullautomation/RobotFramework_AIO/issues/180#issuecomment-1821096018
If you have any useful information that should be added for other users, please let me know.

Best regards,
Thong Hua

2023-11-24 09:52 UTC, test-fullautomation requested changes
Hi Thong,
looks good to me!
Please check my findings.
Thank you,
 Thomas

2023-11-24 09:52 UTC, test-fullautomation commented on build
> +	add_line_to_file "Thomas Pollerspöck <Pollerspoeck@de.bosch.com>"
Hi Thong,
correct is:
thomas.pollerspoeck@de.bosch.com
Thank you,
 Thomas

2023-11-24 09:52 UTC, test-fullautomation commented on build
> +	cp ./Readme.txt ./output_lx/${PACK_NAME}/opt/rfwaio/
Hi Thong,
please let the name "version.txt".
I want to highlight that the version can be found here.
Readme can be a lot of things...
Thank you,
 Thomas

2023-11-24 09:52 UTC, test-fullautomation commented on scripts/RobotFrameworkSetup.iss
> +Source: ..\Readme.txt; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: everyone-full;
same like before.

2023-11-28 09:20 UTC, huavanthong commented
Hi Thomas, 

I have updated it following your comments. 
Please help me merge this request.

Thank you,
Thong Hua

2023-11-28 12:32 UTC, test-fullautomation commented
Hi @huavanthong ,

what about renaming the file to version.txt ?

Thank you,
 Thomas

2023-11-28 12:55 UTC, huavanthong commented
Hi Thomas,

I have updated it at commit https://github.com/test-fullautomation/RobotFramework_AIO/pull/188/commits/a41dd9eb980a5f8a1deda85b2001a305932ebe9c
Could you help me review it?
I’m sorry because I forgot to fix it at your comment directly.

Thank you, 
Thong Hua

2023-11-28 14:16 UTC, merged