Added 'FILES_SAVE' for self tests of Robot Framework
test-fullautomation/RobotFramework_AIO pull request #248
Opened 2024-03-15 09:42 UTC by HolQue

('log_level' test) in TestTrigger configuration

2024-03-15 14:24 UTC, test-fullautomation requested changes
Hi Holger,
looks good to me!
release_info?
Thank you,
 Thomas

2024-03-15 15:51 UTC, HolQue commented
Hi Thomas,

good question. I am not sure. The added information is for the build process, so that the build process knows where to find additional log files. Expected impact is that also the log files of the "log level" self test are part of the downloadable log archive. Are readers of a release mail really interested in such kind of details?

Hmm, I will mention that a new self test is part of the build tool chain. This might be interesting.

2024-03-15 16:07 UTC, HolQue commented
Done

2024-03-18 14:18 UTC, test-fullautomation approved these changes

2024-03-18 14:18 UTC, test-fullautomation commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi Holger,
jupp, thats the end user perspective.
Thank you,
 Thomas

2024-03-18 14:18 UTC, merged