Add prometheus repository
test-fullautomation/RobotFramework_AIO pull request #294
Opened 2024-05-29 03:51 UTC by huavanthong

Hi Thomas,

I have updated the configuration for the prometheus repository to fix the error the pipeline.
Please help me merge it. 

Thank you and best regards,
Thong Hua

2024-05-29 10:02 UTC, test-fullautomation requested changes
Hi Thong,
please see my finding.
Thank you,
 Thomas

2024-05-29 10:02 UTC, test-fullautomation commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi Thong,

this must be part of "0.12.1.;1.13.0." - entry as yesterday written.
Please correct.

Thank you,
 Thomas

2024-05-29 10:20 UTC, huavanthong commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi Thomas, 

I have updated it as your comment.
If I have any mistakes, please let me know.

Thank you,
Thong Hua

2024-05-29 11:38 UTC, test-fullautomation requested changes
Hi Thong,
please check my finding.
Thank you,
 Thomas

2024-05-29 11:38 UTC, test-fullautomation commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi @huavanthong ,

this is unfortunately still wrong.

As written above you  need to make:
 "0.12.1.;0.13.0."

This makes that the info will be visible for intermediate release 0.12.1. and major 0.13.0.
All intermediate version changes need to be visible for this specific intermediate version as well as next major release.

Thank you,
 Thomas

2024-05-29 12:04 UTC, huavanthong commented
Thank you for your pointing. I have updated it.

2024-05-29 14:00 UTC, test-fullautomation requested changes
Hi Thong,
please check my finding.
Thank you,
 Thomas

2024-05-29 14:00 UTC, test-fullautomation commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi @huavanthong ,
better :-)
One "." dot in front of the semicolon is still missing.
This message would be displayed e.g. for 0.12.10, too. But it should be only displayed for 0.12.1. versions.
Thank you,
 Thomas

2024-05-30 03:42 UTC, huavanthong commented on config/robotframework_aio/release_items_Robotframework_AIO.json
Hi Thomas,

I'm sorry for these mistakes. I have updated it and gained a better understanding.
Beside that, I also tested it on my machine. It worked 👍  

Thank you for your support.

Best regards,
Thong Hua

2024-05-30 08:59 UTC, merged